spring:
  banner:
    image:
      location: documentation/drift_logo.png
      margin: 2
      invert: true
server:
  port: 8080
tunnel:
  server:
    enabled: false
    key: "2b625f93-7006-47e2-a469-f41ec3dc7442"
    remoteClient:
      evictDurationInSec: 120
      timeoutInSec: 60
  client:
    enabled: false
    remoteServer:
      url:  ws://localhost:8080
      key: "2b625f93-7006-47e2-a469-f41ec3dc7442"
      ping:
        durationInSec: 10
        delayInSec: 1
        reconnectAfterMaxMisses: 10
    localServer:
      url: http://localhost:8001
      connectTimeoutInSec: 2
      readTimeoutInSec: 2


