server:
  port: 8080

tunnel:
  server:
    key: "2b625f93-7006-47e2-a469-f41ec3dc7442"

  client:
    server:
      url:  http://localhost:8000
      key: "2b625f93-7006-47e2-a469-f41ec3dc7442"
    localServer:
      url: http://localhost:9000


