server:
  port: 8080

tunnel:
  server:
    enabled: true
    key: "2b625f93-7006-47e2-a469-f41ec3dc7442"
    remoteClient:
      evictDurationInSec: 5
      timeoutInSec: 5
  client:
    enabled: true
    remoteServer:
      url:  ws://localhost:8080
      key: "2b625f93-7006-47e2-a469-f41ec3dc7442"
      ping:
        durationInSec: 1
        delayInSec: 1
        reconnectAfterMaxMisses: 10
    localServer:
      url: http://localhost:80
      connectTimeoutInSec: 10
      readTimeoutInSec: 10


